fail_fast: true

repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: Format with Ruff
        entry: uv run ruff format
        language: system
        pass_filenames: false
        always_run: true

      - id: ruff-check
        name: Run Ruff
        entry: uv run ruff check --fix
        language: system
        pass_filenames: false
        always_run: true

      - id: ty-check
        name: Run Ty
        entry: uv run ty check src/relflow --output-format concise
        language: system
        pass_filenames: false
        always_run: true
        verbose: true

      - id: docs
        name: Render Docs
        entry: make render
        language: system
        pass_filenames: false
        always_run: true

      - id: pytest
        name: Run Pytest
        entry: uv run pytest --run-slow
        language: system
        pass_filenames: false
        always_run: true
